server:
  port: 7000

spring:
  application:
    name: nacos-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 10.210.98.75:8848
    gateway:
      routes:
        - id: nacos-consumer
          uri: lb://nacos-consumer
          predicates:
            - Path=/user/**